### ISSUE TITLE
matrix (rather: viz.js) cannot deal with large number of nodes

### ISSUE THREAD

**Issue by lsteinmann** [dainst/idai-field#208]
either limit the number of nodes displayed / passed to viz.js or warn accordingly and disable matrix for affected operation

**Comment by tkleinke** [comment]
I replaced viz.js with the WASM build of Graphviz provided [here](https://github.com/hpcc-systems/hpcc-js-wasm) which turned out to be more performant and reliable. I haven't found a matrix from a Field project yet that cannot be displayed by this, so this should solve this issue for now.

However, there is one particular graph where Graphviz sometimes throws a "Maximum call stack size exceeded" error. It always happens when the dev tools are open (which shouldn’t be a big issue), but also randomly from time to time. For that reason, as a workaround Graphviz is now called again up to 5 times in total in case of an error. When testing this, it always worked the second time, so this should more or less solve the problem. It still seems that there’s a limit to how many nodes and edges Graphviz can process, so I added a warning message that’s shown if SVG generation fails 5 times in a row.
