### ISSUE TITLE
idaifield: There is no category FindCollection in my project

### ISSUE THREAD

**Issue by AKimmig** [dainst/idai-field#265]
In my server project Olympia-context the category FindCollection is not available. In a newly created project it is.

**Comment by lsteinmann** [comment]
Hi! For projects that already existed at the time of the update, the new categories are not automatically included in the configuration. If you click on the + in the lower left of the screen in the project configuration editor, a modal should pop up where you can select and add any of the new categories, including FindCollection. Or is it missing from there?

**Comment by AKimmig** [comment]
Oh thanks, I didn't see that. Which FindCollection should I choose, "FindCollection" or ""FindCollection:default"? And what is the difference?

**Comment by lsteinmann** [comment]
You can see the different form configurations when you select them: FindCollection:default (or anything:default) comes with some pre-configured fields, while the other one is basically a completely empty form that only contains the mandatory core fields which Field needs to be operational. 

I would generally suggest to go with the `:default`-versions so that we have more overlapping fields and valuelists between multiple different projects. But it is of course up to the users to decide.
